@WebApiHost = http://localhost:5220

###
//  REQUEST 1: Get all categories
GET {{WebApiHost}}/v1/cryptocurrency/categories

###
// REQUEST 2: ??? can't find documentation for fetching just the currency data
GET {{WebApiHost}}/v1/cryptocurrency/listings/

###

// REQUEST 3: Get airdrops
GET {{WebApiHost}}/v1/cryptocurrency/airdrop

###

GET {{WebApiHost}}/roles/

###

// REQUEST 4: Get all users
GET {{WebApiHost}}/users/

###

// REQUEST 6: UPDATE user      NOTE: no longer works with more secure user system
PUT {{WebApiHost}}/users/?userId=46682462-d004-4093-a936-ba54843cee2f
Content-Type: application/json

{
    "emailConfirmed" : true
}

###

// REQUEST 7: DELETE user

DELETE {{WebApiHost}}/users/?userId=46682462-d004-4093-a936-ba54843cee2f

###

// REQUEST 8: Get a user
GET {{WebApiHost}}/users/?userId=46682462-d004-4093-a936-ba54843cee2f

###

GET {{WebApiHost}}/https://pro-api.coinmarketcap.com/v1/cryptocurrency/category

###