@WebApiHost = http://localhost:5220


###

POST {{WebApiHost}}/roles/EnterpriseUsers

###

// REQUEST 4: Get all users
GET {{WebApiHost}}/users/

###

GET {{WebApiHost}}/https://pro-api.coinmarketcap.com/v1/cryptocurrency/category

###